openapi: 3.0.0

info:
  title: "Microservices API"
  description: "API for Microservices"
  version: "1.0.0"
servers:
  - url: http://localhost:8083/api/v1
paths: 
  /products/comments:
    post:
      description: "Create new comment"
      tags:
        - "Comments"
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Comment'
      responses:
        201:
          description: "Created"
        401:
          description: "Access Denied"
        422:
          description: "Validation Error"
        500:
          description: "Server Error"
    
  /products/{productId}/comments:
    get:
      description: "Get All Comments by Product ID"
      parameters:
        - in: path
          required: true
          name: productId
          schema:
            type: string
          description: Get comments by product id  
      tags:
        - "Comments"
      responses:
        200:
          description: "OK"
        500:
          description: "Server Error"
  /products/comments/{commentId}:
    get:
      description: "Get Comments Comment ID"
      parameters:
        - in: path
          required: true
          name: commentId
          schema:
            type: string
          description: "Get Comments Comment ID"
      tags:
        - "Comments"
      responses:
        200:
          description: "OK"
        500:
          description: "Server Error"
    put:
      description: "update comment by id"
      tags:
        - "Comments"
      parameters:
      - in: path
        required: true
        name: commentId
        schema:
          type: string
        description: update comment by id  
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              allOf: 
                - $ref: '#/components/schemas/Comment'
      responses:
        200:
          description: "OK"
        403:
          description: "Forbidden"
        404:
          description: "Comment not found"
        422:
          description: "Validation Error"
        500:
          description: "Server Error"
    delete:
      description: "Delete comment by id"
      parameters:
      - in: path
        required: true
        name: commentId
        schema:
          type: string
        description: Delete comment by id  
      security:
        - bearerAuth: []
      tags:
        - "Comments"
      responses:
        200:
          description: "OK"
        403:
          description: "Forbidden"
        404:
          description: "Comment not found"
        500:
          description: "Server Error"
components:
  schemas:
    Comment:
      type: object
      properties:
        content:
          type: string
          example: "Lorem ipsum dolor"
        rating:
          type: number
          example: 2
        productId:
          type: string
          example: "96b46303-46ee-4c94-b774-eaabbf14777e"
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  

    

  